language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.8.1 DJANGO_SETTINGS_MODULE="tpa.settings.test"
install:
  - pip install -r requirements/test.txt
script:
  - cd tpa; coverage run --source='.' manage.py test
after_success:
  - coveralls
